server:
  port: 8080
spring:
  application:
    name: eshop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ConnorLH/springcloud-config-repo.git
          username: ConnorLH
          password: Corner901226
          search-paths: /eshop
          default-label: master
          basedir: /data/config/springcloud-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      prefer-ip-address: true