server:
  port: 8761
spring:
  application:
    name: eshop-eureka
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka